export const ARTIKEL_SHOW_RESET = "ARTIKEL_SHOW_RESET";
export const ARTIKEL_SHOW_SET_ERROR = "ARTIKEL_SHOW_SET_ERROR";
export const ARTIKEL_SHOW_SET_RETRIEVED = "ARTIKEL_SHOW_SET_RETRIEVED";
export const ARTIKEL_SHOW_TOGGLE_LOADING = "ARTIKEL_SHOW_TOGGLE_LOADING";
