export const ARTIKEL_CREATE_RESET = "ARTIKEL_CREATE_RESET";
export const ARTIKEL_CREATE_SET_CREATED = "ARTIKEL_CREATE_SET_CREATED";
export const ARTIKEL_CREATE_SET_ERROR = "ARTIKEL_CREATE_SET_ERROR";
export const ARTIKEL_CREATE_SET_VIOLATIONS = "ARTIKEL_CREATE_SET_VIOLATIONS";
export const ARTIKEL_CREATE_TOGGLE_LOADING = "ARTIKEL_CREATE_TOGGLE_LOADING";
