doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    mapping_types:
      enum: string
    schema_filter: '/(^blog|^passport|^doctrine|^user)/'
    #  tinyint: tinyint
    #types:
    #  tinyint: 'OpenSID\Resource\Doctrine\Type\TinyIntType'
    #types:
    #  tinyint: Kalibora\DoctrineType\TinyintType

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'
  orm:
    auto_generate_proxy_classes: true
    default_entity_manager: default
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
