doctrine_migrations:
  migrations_paths:
    # namespace is arbitrary but should be different from OpenSID\Migrations
    # as migrations classes should NOT be autoloaded
    'DoctrineMigrations': '%kernel.project_dir%/migrations'
  enable_profiler: '%kernel.debug%'
  all_or_nothing: false
  storage:
    # Default (SQL table) metadata storage configuration
    table_storage:
      table_name: 'doctrine_migration_versions'
      version_column_name: 'version'
      version_column_length: 200
      executed_at_column_name: 'executed_at'
