security:
  enable_authenticator_manager: true
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    OpenSID\Security\Model\User:
      algorithm: auto
  providers:
    users:
      entity:
        class: 'OpenSID\Application\Contracts\UserInterface'
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern: ^/login
      stateless: true
      json_login:
        check_path: /login-check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    main:
      pattern: ^/api
      stateless: true
      jwt: ~
      logout:
        path: app_logout

  access_control:
    - { path: ^/login, roles: IS_ANONYMOUS }
    - { path: ^/logout, roles: IS_ANONYMOUS}
    - { path: ^/api/register, roles: IS_ANONYMOUS }
  # - { path: ^/admin, roles: ROLE_ADMIN }
  # - { path: ^/profile, roles: ROLE_USER }
