version: '3.4'
services:
    php:
        container_name: opensid.php
        image: ghcr.io/kilip/opensid/php-dev
        build:
            context: ./
            target: opensid_php
            dockerfile: docker/Dockerfile
        depends_on:
            - database
        restart: unless-stopped
        volumes:
            - php_socket:/var/run/php
        healthcheck:
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 30s

    caddy:
        image: ghcr.io/kilip/opensid/caddy-dev
        container_name: opensid.caddy
        build:
            context: ./
            target: opensid_caddy
            dockerfile: docker/Dockerfile
        depends_on:
            - php
            - pwa
        environment:
            PWA_UPSTREAM: pwa:3000
            SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
            MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY:-!ChangeMe!}
            MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY:-!ChangeMe!}
        restart: unless-stopped
        volumes:
            - php_socket:/var/run/php
            - caddy_data:/data
            - caddy_config:/config
        ports:
            # HTTP
            - target: 80
              published: 80
              protocol: tcp
            # HTTPS
            - target: 443
              published: 443
              protocol: tcp
            # HTTP/3
            - target: 443
              published: 443
              protocol: udp

    pwa:
        image: ghcr.io/kilip/opensid/pwa
        container_name: opensid.pwa
        build:
            context: ./
            target: opensid_pwa_prod
            dockerfile: ./docker/pwa/Dockerfile
        environment:
            OPENSID_CLIENT_GENERATOR_ENTRYPOINT: http://caddy
            NEXT_PUBLIC_ENTRYPOINT: http://caddy

    #database:
    #    container_name: opensid.database
    #    image: postgres
    #    environment:
    #        - POSTGRES_DB=opensid
    #        - POSTGRES_PASSWORD=opensid
    #        - POSTGRES_USER=opensid
    #    ports:
    #        - "5432:5432"
    #    volumes:
    #        - db_data:/var/lib/postgresql/data:rw
    #        - ./docker/postgres/entrypoint:/docker-entrypoint-init.db
    database:
        container_name: 'opensid.database'
        image: 'mariadb:10.3.31'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'opensid'
            MYSQL_USER: 'opensid'
            MYSQL_PASSWORD: 'opensid'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'mariadb:/var/lib/mysql'
            - './docker/mysql/init:/docker-entrypoint-initdb.d'
    phpmyadmin:
        container_name: opensid.phpmyadmin
        image: phpmyadmin
        restart: always
        depends_on:
            -  database
        ports:
            - '1080:80'
        environment:
            - PMA_HOST=database
            - PMA_DATABASE=opensid
            - PMA_USER=opensid
            - PMA_PASSWORD=opensid
volumes:
    php_socket:
    caddy_config:
    caddy_data:
    db_data:
    mariadb:
