version: '3.4'
services:
  php:
    volumes:
      - ./api:/srv/api:rw,cached
      - ./docker/php/conf.d/php.dev.ini:/usr/local/etc/php/conf.d/api_template.ini
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./api/var:/srv/api/var:rw
    environment:
      APP_ENV: dev
      DATABASE_URL: 'postgresql://api_template:api_template@database:5432/api_template?serverVersion=13&charset=utf8'
  caddy:
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./api/public:/srv/api/public:ro
      - ./api/build:/srv/api/build:rw
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo

  pwa:
    image: ghcr.io/kilip/api-platform-template/pwa-dev
    build:
      context: ./
      target: api_template_pwa_dev
      dockerfile: ./docker/pwa/Dockerfile
    volumes:
      - ./pwa:/usr/src/pwa:rw,cached
