version: '3.4'
services:
    php:
        container_name: opensid.php
        image: ghcr.io/kilip/opensid/php-dev
        build:
            context: ./
            target: opensid_php
            dockerfile: ./etc/docker/Dockerfile
        depends_on:
            - database
        restart: unless-stopped
        environment:
            APP_ENV: dev
            DATABASE_URL: 'mysql://root:root@database:3306/opensid'
        volumes:
            - php_socket:/var/run/php
            - ./:/srv/api:rw,cached
            - ./etc/docker/php/conf.d/php.dev.ini:/usr/local/etc/php/conf.d/opensid.ini

        healthcheck:
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 30s

    caddy:
        image: ghcr.io/kilip/opensid/caddy-dev
        container_name: opensid.caddy
        build:
            context: ./
            target: opensid_caddy
            dockerfile: ./etc/docker/Dockerfile
        depends_on:
            - php
            - pwa
        environment:
            PWA_UPSTREAM: pwa:3000
            SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
            MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY:-!ChangeMe!}
            MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY:-!ChangeMe!}
            MERCURE_EXTRA_DIRECTIVES: demo
        restart: unless-stopped
        volumes:
            - php_socket:/var/run/php
            - caddy_data:/data
            - caddy_config:/config
            - ./etc/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
            - ./public:/srv/api/public:ro
        ports:
            # HTTP
            - target: 80
              published: 80
              protocol: tcp
            # HTTPS
            - target: 443
              published: 443
              protocol: tcp
            # HTTP/3
            - target: 443
              published: 443
              protocol: udp

    pwa:
        image: ghcr.io/kilip/opensid/pwa
        container_name: opensid.pwa
        restart: unless-stopped
        build:
            context: ./
            target: opensid_pwa_dev
            dockerfile: ./etc/docker/pwa/Dockerfile
        environment:
            OPENSID_CLIENT_GENERATOR_ENTRYPOINT: http://caddy
            NEXT_PUBLIC_ENTRYPOINT: http://caddy
        volumes:
            - ./pwa:/usr/src/pwa:rw,cached
    database:
        container_name: 'opensid.database'
        image: 'mariadb:10.3.31'
        ports:
            - '3306:3306'
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'opensid'
            MYSQL_USER: 'opensid'
            MYSQL_PASSWORD: 'opensid'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'mariadb:/var/lib/mysql'
            - './etc/docker/mysql/init:/docker-entrypoint-initdb.d'
    phpmyadmin:
        container_name: opensid.phpmyadmin
        image: phpmyadmin
        restart: unless-stopped
        depends_on:
            -  database
        ports:
            - '1080:80'
        environment:
            - PMA_HOST=database
            - PMA_DATABASE=opensid
            - PMA_USER=opensid
            - PMA_PASSWORD=opensid
volumes:
    php_socket:
    caddy_config:
    caddy_data:
    db_data:
    mariadb:
