version: '3.4'
services:
  php:
    volumes:
      - ./api:/srv/api:rw,cached
      - ./docker/php/conf.d/php.dev.ini:/usr/local/etc/php/conf.d/opensid.ini
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./api/var:/srv/api/var:rw
    environment:
      APP_ENV: dev
      DATABASE_URL: 'mysql://root:root@database:3306/opensid'
  caddy:
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./api/public:/srv/api/public:ro
      - ./api/build:/srv/api/build:rw
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo

  pwa:
    image: ghcr.io/kilip/opensid/pwa-dev
    build:
      context: ./
      target: opensid_pwa_dev
      dockerfile: ./docker/pwa/Dockerfile
    volumes:
      - ./pwa:/usr/src/pwa:rw,cached
