export const RESET = "ARTIKEL_LIST_RESET";
export const SET_ITEMS = "ARTIKEL_LIST_SET_ITEMS";
export const SET_ERROR = "ARTIKEL_LIST_SET_ERROR";
export const SET_SELECT_ITEMS = "ARTIKEL_LIST_SET_SELECT_ITEMS";
export const SET_VIEW = "ARTIKEL_LIST_SET_VIEW";
export const TOGGLE_LOADING = "ARTIKEL_LIST_TOGGLE_LOADING";
