parameters:
  opensid.api_prefix: '%env(resolve:OPENSID_API_PREFIX)%'

services:
  _defaults:
    autoconfigure: true
    autowire: true

  app.data_providers.config_item:
    class: OpenSID\Application\DataProvider\ConfigItemDataProvider
    tags: ['api_platform.item_data_provider']
  app.data_providers.user_item:
    class: OpenSID\Application\DataProvider\UserItemDataProvider
    tags: ['api_platform.item_data_provider']
  opensid.app.controllers.logout:
    class: OpenSID\Application\Controller\LogoutController
    tags: [ 'controller.service_arguments' ]
