export const RESET = "ARTIKEL_UPDATE_RESET";
export const SET_ERROR = "ARTIKEL_UPDATE_SET_ERROR";
export const SET_RETRIEVED = "ARTIKEL_UPDATE_SET_RETRIEVED";
export const SET_UPDATED = "ARTIKEL_UPDATE_SET_UPDATED";
export const SET_VIOLATIONS = "ARTIKEL_UPDATE_SET_VIOLATIONS";
export const TOGGLE_LOADING = "ARTIKEL_UPDATE_TOGGLE_LOADING";
export const UPDATE_RETRIEVED = "ARTIKEL_UPDATE_UPDATE_RETRIEVED";
