export const RESET = "KATEGORI_LIST_RESET";
export const SET_ITEMS = "KATEGORI_LIST_SET_ITEMS";
export const SET_ERROR = "KATEGORI_LIST_SET_ERROR";
export const SET_SELECT_ITEMS = "KATEGORI_LIST_SET_SELECT_ITEMS";
export const SET_VIEW = "KATEGORI_LIST_SET_VIEW";
export const TOGGLE_LOADING = "KATEGORI_LIST_TOGGLE_LOADING";
