export const KATEGORI_SHOW_RESET = "KATEGORI_SHOW_RESET";
export const KATEGORI_SHOW_SET_ERROR = "KATEGORI_SHOW_SET_ERROR";
export const KATEGORI_SHOW_SET_RETRIEVED = "KATEGORI_SHOW_SET_RETRIEVED";
export const KATEGORI_SHOW_TOGGLE_LOADING = "KATEGORI_SHOW_TOGGLE_LOADING";
