export const RESET = "KATEGORI_UPDATE_RESET";
export const SET_ERROR = "KATEGORI_UPDATE_SET_ERROR";
export const SET_RETRIEVED = "KATEGORI_UPDATE_SET_RETRIEVED";
export const SET_UPDATED = "KATEGORI_UPDATE_SET_UPDATED";
export const SET_VIOLATIONS = "KATEGORI_UPDATE_SET_VIOLATIONS";
export const TOGGLE_LOADING = "KATEGORI_UPDATE_TOGGLE_LOADING";
export const UPDATE_RETRIEVED = "KATEGORI_UPDATE_UPDATE_RETRIEVED";
