export const KATEGORI_DELETE_RESET = "KATEGORI_DELETE_RESET";
export const KATEGORI_DELETE_SET_ERROR = "KATEGORI_DELETE_SET_ERROR";
export const KATEGORI_DELETE_SET_DELETED = "KATEGORI_DELETE_SET_DELETED";
export const KATEGORI_DELETE_TOGGLE_LOADING = "KATEGORI_DELETE_TOGGLE_LOADING";
