export const KATEGORI_CREATE_RESET = "KATEGORI_CREATE_RESET";
export const KATEGORI_CREATE_SET_CREATED = "KATEGORI_CREATE_SET_CREATED";
export const KATEGORI_CREATE_SET_ERROR = "KATEGORI_CREATE_SET_ERROR";
export const KATEGORI_CREATE_SET_VIOLATIONS = "KATEGORI_CREATE_SET_VIOLATIONS";
export const KATEGORI_CREATE_TOGGLE_LOADING = "KATEGORI_CREATE_TOGGLE_LOADING";
