export const ARTIKEL_DELETE_RESET = "ARTIKEL_DELETE_RESET";
export const ARTIKEL_DELETE_SET_ERROR = "ARTIKEL_DELETE_SET_ERROR";
export const ARTIKEL_DELETE_SET_DELETED = "ARTIKEL_DELETE_SET_DELETED";
export const ARTIKEL_DELETE_TOGGLE_LOADING = "ARTIKEL_DELETE_TOGGLE_LOADING";
